---
- hosts: 192.168.0.21
  tasks:
          - name: retry ping 10 times with exponential backup delay
            ping:
            retries: 10
            delay: "{{ item|int }}"
            loop: "{{ range(1, 10) | map('pow', 2) }}"
...            

