---
- name: Deploy Apache on servers
  hosts: webservers
  tasks:

    - name: install apache
      yum:
        name: "{{ package_name }}"
        state: latest

    - name: create users and add them to the apache group
      user:
        name: "{{ item }}"
        groups: apache
      loop:
        - will
        - myles

    - name: create index.html
      template:
        src: /home/ansible/ansible/ansible/templates/index.j2
        dest: /var/www/html/index.html
        owner: apache
        group: apache
        mode: 0644

    - name: start and enable httpd
      service:
        name: "{{ service_name }}"
        state: restarted
        enabled: yes

- name: Install posgressql
  hosts: dbservers
  tasks:

  - name: Install postgresql
    yum:
      name: "{{ package_name }}"
      state: latest
  
  - name: initialize db cluster
    command: /usr/bin/postgresql-setup --initdb

  - name: create users
    user:
      name: "{{ item }}"
      groups: postgres
    loop:
      - corey
      - aaron

  - name: start and enable postgresql
    service:
      name: "{{ service_name }}"
      state: started
      enabled: yes
...
