---
- name: This Playbook Installs and starts Apache on the servers.
  hosts: webservers 
  tasks:

    - name: Install apache
      package:
        name: "{{ package_name }}"
        state: latest

    - name: Make sure service is started
      service:
        name: "{{ service_name }}"
        state: started
        enabled: yes

    - name: Adding html index file.
      copy:
        src: /home/ansible/ansible/playbooks/index.html
        dest: /var/www/html/

    - name: Opening Firewall for Service!
      firewalld:
        zone: public      
        service: http
        permanent: yes
        state: enabled

    - name: Opening Firewall Port!
      firewalld:
        zone: public      
        port: 80/tcp
        permanent: yes
        state: enabled    

    - name: Restarting Firewalld!
      service: 
        name: firewalld
        state: restarted    

    - name: Update httpd.conf
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen.*$'
        replace: 'Listen 90'
        backup: yes
      notify: 
        - "Close port 80"
        - "Open port 90"
        - "Restart firewall & Apache"
        - "Apply SELinux port type"


  handlers:
    - name: "Apply SELinux port type"
      seport:
        ports: 90
        proto: tcp
        setype: http_port_t
        state: present

    - name: "Close port 80"
      firewalld:
        zone: public
        port: 80/tcp
        state: disabled

    - name: "Open port 90"
      firewalld:
        zone: public
        port: 90/tcp
        permanent: yes
        state: enabled

    - name: "Restart firewall & Apache"
      service:
        name: "{{ item }}" 
        state: restarted
      with_items:
        - firewalld
        - "{{ service_name }}"
...
